# -*- coding: utf-8 -*-
"""Sprites recortados de la referencia, recoloreados a verde STLabs.
El hombrecito original era celeste; acá replica la grilla 8-bit y pasa a #00FFB2
con contorno sticker blanco. Claude se rasteriza del SVG oficial (estrella naranja).
"""
from pathlib import Path
from PIL import Image

A = Path(__file__).resolve().parent / "assets"
G = (0, 255, 178, 255)
W = (255, 255, 255, 255)
EYE = (180, 255, 230, 255)
METAL = (160, 170, 175, 255)
DARK = (40, 80, 90, 255)
BELL2 = (0, 200, 150, 255)
CELL = 12


def paint(rows, mapping, outline=True):
    h, w = len(rows), max(len(r) for r in rows)
    grid = [[None] * w for _ in range(h)]
    for y, row in enumerate(rows):
        for x, ch in enumerate(row.ljust(w)):
            if ch in mapping:
                grid[y][x] = mapping[ch]
    if outline:
        out = [row[:] for row in grid]
        for y in range(h):
            for x in range(w):
                if grid[y][x]:
                    continue
                for dy, dx in ((-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (-1, 1), (1, -1), (1, 1)):
                    ny, nx = y + dy, x + dx
                    if 0 <= ny < h and 0 <= nx < w and grid[ny][nx]:
                        out[y][x] = W
                        break
        grid = out
    img = Image.new("RGBA", (w * CELL, h * CELL), (0, 0, 0, 0))
    px = img.load()
    for y in range(h):
        for x in range(w):
            if not grid[y][x]:
                continue
            col = grid[y][x]
            for yy in range(y * CELL, (y + 1) * CELL):
                for xx in range(x * CELL, (x + 1) * CELL):
                    px[xx, yy] = col
    return img


def save(img: Image.Image, name: str):
    img.save(A / name)
    print("wrote", name, img.size)


DUDE = """
......................
......................
..........##..........
.........####.........
.........##o#.........
.........####.........
..........##..........
........######........
.......#.####.#.......
.......#.####.#.......
.........####.........
.........#..#.........
.........#..#.........
........##..##........
......................
......................
""".strip("\n").split("\n")

WRENCH = """
......................
......................
..........##..........
.........####.........
.........####.........
..........##..........
........######........
.......#.####.#.......
....ggg#.####.#gg.....
....g.g..####..g......
....ggg..#..#.........
.........#..#.........
........##..##........
......................
......................
""".strip("\n").split("\n")

COST = """
......................
......................
..........##..........
.........####.........
.........####.........
..........##..........
........######........
.......x.####.x.......
.......xxxxxxxx.......
.......x..##..x.......
.......x.####.x.......
.......x..##..x.......
.........#..#.........
........##..##........
......................
......................
""".strip("\n").split("\n")

BELL = """
......................
......................
..........##..........
.........####.........
.........####.........
..........##..........
........######........
.......#.####.#.......
.......########.......
.......##.##.##.......
........######........
..........##..........
.........#..#.........
........##..##........
......................
......................
""".strip("\n").split("\n")


def raster_claude():
    """Raster del SVG oficial (estrella naranja de puntas redondas) a PNG transparente."""
    try:
        import cairosvg
    except ImportError:
        return
    svg = (A / "claude.svg").read_bytes()
    out = A / "claude.png"
    cairosvg.svg2png(bytestring=svg, write_to=str(out), output_width=512, output_height=512)
    im = Image.open(out).convert("RGBA")
    # quitar fondo casi negro si el renderer lo pintó
    px = im.load()
    w, h = im.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            if r < 20 and g < 20 and b < 20:
                px[x, y] = (0, 0, 0, 0)
    im.save(out)
    print("wrote claude.png", im.size)


def main():
    body = {"#": G, "o": EYE, "g": METAL, "x": DARK, "+": BELL2}
    save(paint(DUDE, body), "pixel-dude.png")
    save(paint(WRENCH, body), "pixel-wrench.png")
    save(paint(COST, body), "pixel-cost.png")
    save(paint(BELL, body), "pixel-bell.png")
    raster_claude()


if __name__ == "__main__":
    main()
